---
- name: Apply new nodes names (Update EE_ID)
  hosts: gpu_nodes
  become: true
  vars:
    ansible_roles_path: "{{ playbook_dir }}/../roles"
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/vault.yml
    - ../group_vars/mnl.yml
    - ../group_vars/variables.yml
  tasks:
    - name: Update node names (EE_ID configuration)
      include_tasks: ../roles/setup/tasks/update_node_names.yml 