---
- name: reboot system
  reboot:
    msg: "Reboot triggered by NVIDIA driver installation"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime 