---
- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Update package cache (RHEL)
  dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install required packages (Debian/Ubuntu)
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - build-essential
      - git
    state: present
  when: ansible_os_family == "Debian"

- name: Install required packages (RHEL)
  dnf:
    name:
      - ca-certificates
      - curl
      - dnf-plugins-core
      - python3-pip
      - gcc
      - gcc-c++
      - make
      - git
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure system is updated (Debian/Ubuntu)
  apt:
    upgrade: full
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure system is updated (RHEL)
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat" 