---
- name: Remove old Docker installations and configurations
  block:
    - name: Remove old Docker packages
      package:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Remove Docker repository configuration
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/sources.list.d/docker.list
        - /etc/apt/keyrings/docker.asc
        - /etc/apt/trusted.gpg.d/docker.gpg

    - name: Clean apt cache
      command: apt-get clean
      changed_when: false

- name: Install prerequisites
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Create Docker keyring directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Execute Docker installation script
  command: /tmp/get-docker.sh
  register: docker_install
  changed_when: docker_install.rc == 0
  failed_when: false  # Don't fail if Docker is already installed

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Clean up installation script
  file:
    path: /tmp/get-docker.sh
    state: absent 