---
- name: Remove old Docker versions
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install prerequisites
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Download Docker installation script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Execute Docker installation script
  command: /tmp/get-docker.sh
  register: docker_install
  changed_when: docker_install.rc == 0
  failed_when: docker_install.rc != 0

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Clean up installation script
  file:
    path: /tmp/get-docker.sh
    state: absent 