- name: Wait for 20 seconds
  ansible.builtin.pause:
    seconds: 20

- name: Run get_node_info command
  ansible.builtin.shell: get_node_info
  register: node_info
  ignore_errors: true

- name: Display node information
  debug:
    var: node_info.stdout_lines
  when: node_info.stdout_lines is defined

- name: Display error if command failed
  debug:
    var: node_info.stderr_lines
  when: node_info.stderr_lines is defined and node_info.stderr_lines | length > 0
