---
#- name: Setup services
#  systemd:
#    name: my_service  # Replace with your actual service name
#    state: started
#    enabled: yes
#  when: ansible_os_family == "Linux"

# Add more service-related tasks here


- name: "Create service for {{ mnl_app_name }}"
  ansible.builtin.template:
    src: mnl_ee.service.j2
    dest: /etc/systemd/system/{{ mnl_app_name }}.service
    mode: '0644'
    force: true
  notify: reload systemd
