---
# Docker configuration
docker_compose_version: "2.23.3"

# NVIDIA configuration
nvidia_driver_version: "535"  # Change this to match your needs
cuda_version: "12.2"

# Docker image configuration
docker_image_name: "naeural/edge_node:develop"  # Replace with your image name
docker_registry: ""  # Add your registry if needed 