---
all:
  children:
    gpu_nodes:
      hosts:
        # Add your GPU nodes here
        # Example:
        # gpu-node-1:
        #   ansible_host: 192.168.1.100
        #   ansible_user: ubuntu
        #   ansible_ssh_private_key_file: ~/.ssh/id_rsa 
        ubuntu-vm:
          ansible_host: 192.168.0.208
          ansible_user: vv
          ansible_become_password: 1  # For sudo privileges
          ansible_connection: ssh
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_pass: "1"                        # the password to connect to the remote host if no private key is used
          # Since this is a local VM, we can disable host key checking
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 
        ubuntu-vm-2:
          ansible_host: 192.168.0.208
          ansible_user: vv
          ansible_become_password: 1  # For sudo privileges
          ansible_connection: ssh
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_pass: "1"                        # the password to connect to the remote host if no private key is used
          # Since this is a local VM, we can disable host key checking
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
